services:
  db:
    image: pgvector/pgvector:pg16
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer
    ports:
    - 8080:8080
