server:
  port: 8091
spring:
  application:
    name: rag-openai-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  ai:
    azure:
      openai:
        # The Key from Azure AI OpenAI Keys and Endpoint section under Resource Management
        api-key:
        # The Key from Azure AI OpenAI Keys and Endpoint section under Resource Management
        endpoint:
        embedding:
          options:
            deployment-name: text-embedding-3-small # Azure deployment (not model) name
        chat:
          options:
            deployment-name: gpt-4o-mini # Azure deployment (not model) name
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE # Search distance type. Defaults to COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: true
        #schema-validation: true # Set to true only if you use other schema and table name than defaults.